---

- name: Install apps
  package:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - strongswan
    - strongswan-pki
    - libcharon-extra-plugins
    - libcharon-extauth-plugins