---

- name: Install strongswan
  package:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - strongswan
    - strongswan-pki
    - libcharon-extra-plugins
    - libcharon-extauth-plugins
    - libstrongswan-extra-plugins
    - libtss2-tcti-tabrmd0
    - strongswan-swanctl