---

# install apps
- import_tasks: install.yml

- name: Check that /etc/ipsec.d/private/ca-key.pem exists
  stat:
    path: /etc/ipsec.d/private/ca-key.pem
  register: stat_result

# create sertification centre and generate cert for VPN server if
# /etc/ipsec.d/private/ca-key.pem doesn't exist
- import_tasks: generate_certs.yml
  when: not stat_result.stat.exists or generate_certs is defined

# setup strongswan vpn
- import_tasks: strongswan_config.yml

# ufw config
- import_tasks: ufw_config.yml

# restart strongswan if ipsec_restart=true
- name: Restart strongswan by ipsec_restart command
  service:
    name: strongswan-starter
    state: restarted
  when: ipsec_restart is defined

