---

- name: generate ipsec.conf
  template:
    src: ipsec.conf
    dest: /etc/ipsec.conf
  notify:
    - Restart strongswan

- name: copy ipsec.secrets
  copy:
    src: ipsec.secrets
    dest: /etc/ipsec.secrets
  notify:
    - Reread ipsec.secrets

