---

- name: Install ufw
  package:
    name: ufw
    state: present

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  loop:
    - { direction: "incoming", policy: "deny" }
    - { direction: "outgoing", policy: "allow" }
  notify:
    - Restart ufw

- name: Configure ufw rules
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  loop:
    - { rule: "limit", port: "{{ ssh_port | default('22') }}", proto: "tcp" }
    - { rule: "allow", port: "500", proto: "udp" }
    - { rule: "allow", port: "4500", proto: "udp" }
  notify:
    - Restart ufw

- name: Enable ufw
  ufw: state=enabled

# add lines if doesn't exist
- name: Configure /etc/ufw/sysctl.conf
  lineinfile:
    path: /etc/ufw/sysctl.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "net/ipv4/ip_forward=1"
    - "net/ipv4/conf/all/accept_redirects=0"
    - "net/ipv4/conf/all/send_redirects=0"
    - "net/ipv4/ip_no_pmtu_disc=1"
  notify:
    - Restart ufw

- block:
    - name: insert *nat and * mangle into /etc/ufw/before.rules
      blockinfile:
        path: /etc/ufw/before.rules
        insertbefore: '\*filter'
        marker: "# {mark} ANSIBLE MANAGED BLOCK *nat * mangle"
        block: |
          *nat
          -A POSTROUTING -s {{ vpn_subnet }} -o {{ interface }} -m policy --pol ipsec --dir out -j ACCEPT
          -A POSTROUTING -s {{ vpn_subnet }} -o {{ interface }} -j MASQUERADE
          COMMIT

          *mangle
          -A FORWARD --match policy --pol ipsec --dir in -s {{ vpn_subnet }} -o {{ interface }} -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 -j TCPMSS --set-mss 1360
          COMMIT

    - name: insert ufw-before-forward into /etc/ufw/before.rules
      blockinfile:
        path: /etc/ufw/before.rules
        insertafter: '# End required lines'
        marker: "# {mark} ANSIBLE MANAGED BLOCK ufw-before-forward"
        block: |
          -A ufw-before-forward --match policy --pol ipsec --dir in --proto esp -s {{ vpn_subnet }} -j ACCEPT
          -A ufw-before-forward --match policy --pol ipsec --dir out --proto esp -d {{ vpn_subnet }} -j ACCEPT
  notify:
    - Restart ufw
