---

- name: Restart strongswan
  service:
    name: strongswan-starter
    state: restarted

- name: Restart ufw
  service:
    name: ufw
    state: restarted

- name: Reread ipsec.secrets
  shell: ipsec rereadsecrets