---

# install UFW
- import_tasks: install.yml

# UFW configuration
- name: UFW ssh allow
  ufw:
    rule: allow
    port: "{{ ansible_port | default('ssh') }}"
    proto: tcp

- name: UFW 500/udp Allow
  ufw:
    rule: allow
    port: 500
    proto: udp

- name: UFW 4500/udp Allow
  ufw:
    rule: allow
    port: 4500
    proto: udp

- name: UFW 80/tcp Allow
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: UFW 443/tcp Allow
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: UFW default outgoing Allow
  ufw:
    state: enabled
    direction: outgoing
    default: allow

- name: UFW default incoming Deny
  ufw:
    state: enabled
    direction: incoming
    default: deny

# add lines if it doesn't exist
- name: Configure /etc/ufw/sysctl.conf
  lineinfile:
    path: /etc/ufw/sysctl.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "net/ipv4/ip_forward=1"
    - "net/ipv4/conf/all/accept_redirects=0"
    - "net/ipv4/conf/all/send_redirects=0"
    - "net/ipv4/ip_no_pmtu_disc=1"
  notify:
    - Restart ufw

# ufw rules ipv4
- import_tasks: ufw_rules/ipv4_rules.yml

# ufw rules ipv6
- import_tasks: ufw_rules/ipv6_rules.yml